src/components/site-navigation/site-navigation.yml
src/pages/components/card.md
src/pages/components/container.md
src/pages/components/textarea.md
src/pages/patterns/sign-in.md

I had to simply add the component sandbox to the nav yaml.
And the add the card, container and textarea to the pages and nav yaml.

Add missing pages to site nav

---

.vscode/extensions.json

This change adds the list of VSCode extensions that we recommendation for all contributors to the project.

feat: add project extensions

---

src/components/site-navigation/site-navigation.yml
src/pages/getting-started/index.md

I ordered the nav > components section alphabetically.

refactor: order nav > components alphabetically

---

src/components/home/signup/home-signup.css

Updated the sizing properties/spacing for the sign up form on the homepage.

(homepage-redesign): updated css sizing properties for sign up form

---

src/components/site-footer/site-footer.astro
src/data/home-community.json

Ported over the footer changes and also updated the community events to more current info

footer fixes and update to community events

---

src/components/site-navigation/site-navigation.css

Removed the css --mask attribute that was causing the gradient.

fix: visual bug where there was a gradient at the bottom of the nav if the search was active on desktop.

---

src/components/home/signup/home-signup.astro
src/data/home-signup.json
src/layouts/docs/docs-layout.client.js
src/layouts/docs/docs-layout.css
src/pages/support.astro

I cleared the error using some of the knowledge that Jonathan gave me [here](https://github.com/RocketCommunicationsInc/astro-www/commit/a718b31f16416f9ddfd4f91fa00173569d8703ad).
Afterwards, and upon a more in-depth discussion with Jonathan I now understand how this works and have also fixed the form on the support page. This should be good to go!
Jira: [ASTRO-4829](https://rocketcom.atlassian.net/browse/ASTRO-4829)

fixed console error on homepage regarding Mailchimp

---

src/pages/design-guidelines/glossary.md
src/pages/getting-started/developers.md
src/pages/patterns/modeless-panes.md

fix: remove 404s

---

src/components/home/articles/home-articles.astro
src/components/home/articles/home-articles.css
src/components/slideshow/slideshow.css
src/data/home-articles.json
src/data/home-community.json

The articles carousel wasn't sized properly for mobile devices. Fixed the padding and a couple of other odds and ends so that it would be.

updates to articles carousel for mobile

---

src/data/home-community.json

event updates, soon to be a thing of the past when Daniel N and I implement the new calendar!

update(events) : manual events update

---

package.json
src/pages/design-tokens/component.astro

update tokens 1.1

---

src/data/home-community.json

just updating the community events while waiting for the calendar integration

refresh events

---

src/data/compliance.json
src/data/home-articles.json
src/data/home-banner.json
src/data/home-community.json
src/data/home-signup.json
src/data/navigation.json

Fix PR corrects issues in our JSON data files:
1. Changes the navigation link from `/components/pop-up/` to `/components/pop-up-menu/ `.
2. Applies the formatter to all of our JSON data files.

Update JSON data

---

src/components/home/community/home-community.css

events cal was unsettled on mobile screen size. fixed.

mobile events fix

---

src/pages/components/pop-up-menu.md

this is a small ticket that preps rux-pop-up-menu moving from a component to a pattern.
https://rocketcom.atlassian.net/browse/ASTRO-5098

rux-pop-up-menu: change default story in preparation for it becoming a pattern.

---

src/pages/components/accordion.md

[ASTRO-4920](https://rocketcom.atlassian.net/browse/ASTRO-4920)
Changes to Accordion page

changes to accordion page

---

src/pages/patterns/table.md

As per [ASTRO-4925](https://rocketcom.atlassian.net/browse/ASTRO-4925)

Tables documentation update

---

src/pages/community/content-policy.md

This page was still referencing the master branch, now called main

Change refs from master to main branch, as its now named.

---

src/components/compliance/compliance.css
src/data/compliance.json
src/pages/components/dialog.md

Updated dialog page along with its corresponding compliance data.
I also added a 'new' status for compliance since it seems like that status is being added in the confluence page. 
[ASTRO-4926](https://rocketcom.atlassian.net/browse/ASTRO-4926)

update dialog page and compliance data

---

src/pages/components/tooltip.md

[ASTRO-5241](https://rocketcom.atlassian.net/browse/ASTRO-5241)
Change wording on tooltip page

change pop up menu to pop up

---

src/pages/getting-started/index.md
src/pages/releases/index.astro

[ASTRO-5252](https://rocketcom.atlassian.net/browse/ASTRO-5252)
change copyright on the site. It only appears on the getting started page. There is a separate ticket to put it in the footer but no one could decide on the wording so that one is stopped for now.

 copyright changes & relevant year change

---

src/data/compliance-footer.json
src/data/compliance.json

Updating compliance version on Compliance page and compliance footer.

chore(compliance): Update compliance version number from 3.2.0 to 4.1.0

---

src/pages/patterns/breadcrumbs.md

[ASTRO-5460](https://rocketcom.atlassian.net/browse/ASTRO-5460)
Updated Breadcrumb Pattern page with updated guidance, dos and donts

update breadcrumb page

---

src/pages/patterns/breadcrumbs.md

[ASTRO-5367](https://rocketcom.atlassian.net/browse/ASTRO-5367)
Added storybook link to be merged when Breadcrumb web component releases. 🎉

doc(breadcrumb) add storybook link for release today

---

src/components/site-footer/site-footer.astro
src/components/site-footer/site-footer.css

[ASTRO-4801](https://rocketcom.atlassian.net/browse/ASTRO-4801)
Added the copyright beneath 'provided by' wording as suggested and confirmed by Emily.
It also looks like saving the css file organized it according to a standard it wasn't using. So that's what all the deletions and adds are. I didn't actually remove anything.

add copyright - suggested placement

---

.vscode/vite-plugins.js
.vscode/vite-plugins/vite-minify-raw.js
.vscode/vite-plugins/vite-postcss.js
package.json
src/env.d.ts

Fix issues when Astro is running the latest versions.

Fix breaking changes in Astro build

---

src/pages/components/tooltip.md

JIRA: https://rocketcom.atlassian.net/browse/ASTRO-5608
Adds additional info about when to use tooltips vs pop-ups. Text may change based on design review.

docs(tooltip): rules of thumb update

---

src/utils/client/google-analytics.ts

[ASTRO-5648](https://rocketcom.atlassian.net/browse/ASTRO-5648)
Google Analytics was not analyzing data correctly so I made a small change to the code snippet.This fix allows google analytics to properly process the incoming data.

bug(analytics) Analytics is not processing data

---

src/pages/design-tokens/reference/index.astro

https://rocketcom.atlassian.net/browse/ASTRO-5594
Move color tokens from Font Weight category to Colors and remove duplicate Font Weight category
Remove control-1 typography tokens from Font Weight category
Add correct font weight tokens under Font Weight category
Add body-1, body-1-bold, body-2, body-2-bold, body-3, body-3-bold, control-body-1, and control-body-1-bold typography tokens under Typography section

update reference token page

---

src/pages/getting-started/designers.md

[ASTRO-5645](https://rocketcom.atlassian.net/browse/ASTRO-5645)
Added links to the 7.0 Wireframe and Light themes.

docs(getting started) Add links for 7.0 wireframe and light themes

---

src/components/icon-search/icon-search.client.ts
src/components/icon-search/parts/side-panel.shadow.css

[ASTRO-5733](https://rocketcom.atlassian.net/browse/ASTRO-5733)

fix(icon library) adjust side panel to account for small screens

---

src/pages/design-tokens/installation.md

https://rocketcom.atlassian.net/browse/ASTRO-5774

added json/nested token docs

---

src/pages/patterns/pop-up-menu.md

https://rocketcom.atlassian.net/browse/ASTRO-5763
Update was already made in Confluence.

docs(pop-up-menu): typo fix

---

src/pages/components/button.md

https://rocketcom.atlassian.net/browse/ASTRO-5763
Update was already made in Confluence.

docs(button): typo fix and added info

---

src/pages/releases/index.astro

Release for 3-30-23. 
WC: 9.7.1 -> 9.7.2
Figma Dark: 7.3.1 -> 7.4
Figma Light: 7.0.1 -> 7.1
Figma WF: 7.0.1 -> 7.1

release: 3-30-23

---

package.json
src/pages/design-tokens/system/index.astro
src/utils/tokens.ts

Adds data viz system tokens and new container bgs

docs: update tokens 1.6

---

src/pages/components/input-field/specs.md

add missing content for input spec pages

add missing content

---

src/components/asset-status/asset-status.astro
src/components/asset-status/asset-status.css
src/components/asset-status/asset-status.keyToggleHandler.js

[ASTRO-5942](https://rocketcom.atlassian.net/browse/ASTRO-5942)
Added a dropdown that lists each status to Asset Status on mobile sizes (width < 450px)

Add status dropdown to mobile version of Asset Status

---

package.json
src/pages/design-tokens/component/index.astro
src/pages/design-tokens/reference/index.astro
src/pages/design-tokens/system/index.astro
src/utils/tokens.ts

Updates documentation tokens to 1.7.

tokens@1.7 docs

---

src/layouts/new-docs/style/page.css
src/pages/components/button/specs.md

this is a test for Emily so that we can get an acceptable amount of difference between h3 and h4

H3 size change on new docs pages

---

src/pages/components/button/specs.md
src/pages/components/input-field/specs.md
src/pages/components/select/specs.md
src/pages/components/textarea/specs.md

I done goofed. the padding tokens should be flipped x = left/right, y = top/bottom

flip x/y padding tokens

---

src/data/asset-status.json

[ASTRO-6009](https://rocketcom.atlassian.net/browse/ASTRO-6009)
I updated the json file to reflect the status updates in this ticket.

update to asset status json to reflect versions

---

src/components/asset-status/asset-status.astro
src/components/asset-status/asset-status.keyToggleHandler.js
src/utils/tokens.ts

This change fixes files that had minor issues picked up by our linters.
We do not require linting to commit files, and so occasionally we need to commit linting fixes on their own.

Fixes applied by npm checks

---

src/data/navigation.json

[Astro-5954](https://rocketcom.atlassian.net/browse/ASTRO-5954)

fix(nav) alphabetize patterns section in main navigation

---

src/pages/components/slider/index.md

Removing this line that no longer makes any sense. It was relevant for like Astro 4

update slider content

---

src/data/compliance.json
src/pages/components/pop-up.md

[ASTRO-6066](https://rocketcom.atlassian.net/browse/ASTRO-6066)

docs(compliance) pop up add new compliance rule

---

CUSTOM_ELEMENTS.md

[Preview](https://github.com/RocketCommunicationsInc/astro-www/blob/jn.add-custom-element-docs/CUSTOM_ELEMENTS.md)
This change adds documentation for the custom elements used on the Astro WWW page. Those elements are the Feedback Widget, Icon Panel, Navigation Disclosure, Navigation List, Slideshow, and Color Swab.

Document Custom Elements used on Astro WWW

---

src/components/feedback-widgets/feedback-widget-custom-element.ts

I'm not sure if this is already addressed some place else, feel free to close

refactor(feedback-widget): rm console.log

---

src/pages/patterns/data-visualization/index.md

[astro-5785](https://rocketcom.atlassian.net/browse/ASTRO-5785)

docs(data viz) add color guidance to data visualization page

---

src/layouts/home/home-layout.astro
src/layouts/home/home-layout.css

home page would not scroll. this small update corrects that

fix(homepage) correct homepage scrolling

---

astro.config.js
package.json
src/pages/design-tokens/component/index.astro
src/pages/design-tokens/component/light.astro
src/pages/design-tokens/reference/index.astro
src/pages/design-tokens/system/index.astro
src/pages/design-tokens/system/light.astro

Implements the [Lit SSR integration](https://docs.astro.build/en/guides/integrations-guide/lit/) for better perf on the token pages.

feat: lit ssr integration

---

src/pages/components/segmented-button.md

[Astro-6178](https://rocketcom.atlassian.net/browse/ASTRO-6178)
This was just waiting on a small fix to astro components. now that it's in, segmented button can release on playground. :)
(I purged jsdelivr's cache so that it would take the latest version of web components)

feat(segmented button) add playground to segmented button

---

astro.config.js
package.json
src/layouts/default/default-layout.astro

adds sitemap to https://deploy-preview-254--astrouxds.netlify.app/sitemap-index.xml 
ASTRO-6264

feat: sitemaps

---

src/pages/migration/index.astro

Quick typo fix for the code snippet on the migration page.

fix(migration): lin -> link

---

src/components/icon-search/parts/side-panel.shadow.css
src/components/icon-search/parts/side-panel.ts

[ASTRO-6213](https://rocketcom.atlassian.net/browse/ASTRO-6213)
I wrote a little addition to side panel that makes the tags clickable. Clicking them populates the search input and initiates a search.

feat(icon library) make keywords clickable in side panel

---

src/data/asset-status.json
src/pages/releases/index.astro

Updates release page, updates asset status on datepicker

chore: release

---

src/pages/getting-started/index.md

Updated Getting Started
Changed SMC/Space Missile Command to SSC/Space Systems Command
Updated support email from UXsupport@rocketcom.com to support@astrouxds.com

Updated Getting Started

---

src/pages/components/button/index.md

button docs

---

src/layouts/docs/style/heading-anchors.css
src/layouts/docs/style/page.css
src/layouts/docs/style/utilities.css
src/pages/design-tokens/getting-started/index.astro

This changes our largest site breakpoint (the one that hides the sidebar) from 1728px down to 1294px.
I have added a couple of additional tweaks to wide tables to make sure they honor the new convention.
[Astro-6295](https://rocketcom.atlassian.net/browse/ASTRO-6295)

feat(sitewide) change large breakpoint from 1728px to 1294px 

---

src/pages/releases/index.astro

Updates versions on release page for 7.13 release.

chore: release page for 7.13

---

src/layouts/default/style/variables.css
src/layouts/docs/style/page.css
src/layouts/docs/style/variables.css
src/pages/patterns/forms-and-validation.md
src/pages/stylesheet.md

[ASTRO-6356](https://rocketcom.atlassian.net/browse/ASTRO-6356)
new note styles

feat(notes) new note styles

---

src/data/global.json
src/layouts/default/default-layout.astro
src/layouts/docs/docs-layout.astro

[ASTRO-6348](https://rocketcom.atlassian.net/browse/ASTRO-6348)
Changed the meta description tag to take on a description from the frontmatter of a page if it has one and default to a generic one if not.

feat(description meta) Change description meta tag to take on the description under page title

---

src/pages/patterns/table/index.md

Added expanded guidance that makes it more clear additional default sorting options are allowable. Note: compliance does not require a default sort.

Update table sorting guidance

---

src/layouts/docs/style/page.css

Not a ticket just a quick nit fix.

fix(responsive) small tweak for  1920px > screens >= 1440

---

src/pages/downloads.md

can we just....put these pdfs in here like this?
context: https://rocketcom.atlassian.net/wiki/spaces/AS11/pages/2749726721/Deprecated+Content+List
pruning all the deprecated content. removing the 2 TTC bois until we complete them

update downloads page

---

netlify.toml
src/components/compliance/compliance.astro
src/components/site-footer/site-footer.astro
src/data/compliance-footer.json
src/data/compliance.json
src/data/navigation.json
src/pages/community/content-policy.md
src/pages/compliance/index.astro
src/pages/compliance/r2c2-design-compliance/index.astro
src/pages/design-guidelines/compliance/index.astro
src/pages/fd-service-ux-design/about-the-fd-designs.md
src/pages/getting-started/designers.md
src/pages/getting-started/developers.md
src/pages/getting-started/index.md
src/pages/grm-service-ux-design/about-the-grm-designs.md
src/pages/grm-service-ux-design/grm-dashboard.md
src/pages/grm-service-ux-design/grm-equipment-manager.md
src/pages/grm-service-ux-design/grm-schedule.md
src/pages/platforms/_astro-for-r2c2.md
src/pages/service-specific-ux-design.md
src/pages/ttc-service-ux-design/about-the-ttc-designs.md
src/pages/ttc-service-ux-design/ttc-command.md
src/pages/ttc-service-ux-design/ttc-investigate.md
src/pages/ttc-service-ux-design/ttc-monitor.md

Updated all found reference from EGS to R2C2

Egs to r2c2 content

---

src/data/navigation.json
src/data/navigation.secondary.json

Adds tabs for GRM and TTC apps. Removes them from the sidebar. consolidates everything under one new case studies top level nav item.

case studies

---

src/pages/components/tabs.md

[ASTRO-6473](https://rocketcom.atlassian.net/browse/ASTRO-6473)

docs(tabs) fix note layout

---

src/pages/releases/index.astro

Updates release page 
WC -> 7.15.2
Dark theme -> 7.8
Light theme -> 7.6 
Wireframe -> 7.6

update releases page

---

src/data/component-playgrounds.record.json

[ASTRO-6604](https://rocketcom.atlassian.net/browse/ASTRO-6604)
Instead of removing the menu I set it as a secondary example.

docs(popup) change default example

---

src/components/component-playground/IFrameLayout.ts

notices a playground visual bug when the playground was < 700px wide. fixed that. there's not a ticket for this one

fix bug on playground for < 700 wide

---

src/layouts/docs/style/page.css
src/pages/patterns/table/index.md

Add design token example and headless tables example with companion code sandbox iframes

BK ASTRO-6593 Document usage with tanstack table

---

src/pages/releases/index.astro

Updates release page with new WC version and new tokens version

chore: update release page

---

src/pages/platforms/astro-for-r2c2.md

Recommend adding this section that covers XTCE Alarm color alignment to C2MS and AstroUX.  Please contact me if you have questions.

XTCE alignment

---

src/pages/platforms/astro-for-r2c2.md

Reverts RocketCommunicationsInc/astro-www#311

Revert "XTCE alignment"

---

src/layouts/docs/style/utilities.css
src/pages/platforms/astro-for-r2c2.md

Additionally I changed some scripting to make the color samples and status symbols show up in this new table and modified the dark tables so that they didn't have odd lines on HD screens.
[ASTRO-6680](https://rocketcom.atlassian.net/browse/ASTRO-6680)

docs(r2c2) Add XTCE table to site

---

src/utils/tokens.ts

some of the system tokens weren't appearing on light theme so small tweak to the system function.

tweak system tokens

---

src/pages/grm-service-ux-design/about-the-grm-designs.md

Updating content for better readability and to be more accurate to the latest demo apps. ASTRO-6779 and ASTRO-6857 related.
https://rocketcom.atlassian.net/browse/ASTRO-6779
https://rocketcom.atlassian.net/browse/ASTRO-6857
https://rocketcom.atlassian.net/wiki/spaces/AWS/pages/2976350314/Ground+Resource+Management

Update about-the-grm-designs.md text

---

src/components/home/community/home-community-events.astro
src/components/home/community/home-community.css

removing the latest events for astro puts us in a situation where there are no events. added a contingency for that.

add no-events indicator

---

src/pages/platforms/astro-for-r2c2.md

Fix spelling error of "FALED" to "FAILED"

Update astro-for-r2c2.md to fix a spelling error

---

src/components/feedback-widgets/feedback-widget-custom-element.shadow.html

Replaces the feedback action url with the new feedback endpoint

Update submitted feedback endpoint

---

src/pages/patterns/table/index.md

This PR makes changes to our AG Grid Astro theme documentation to reflect the recent changes in the 8.0.0 release.

chore(patterns > table > ag-grid-theme): Updating ag grid astro theme docs and code examples

---

src/data/compliance.json

Fixed typo where optional fields were also marked with asterisks.

Update compliance.json for optional typo

---

src/data/asset-status.json
src/pages/components/getting-started.md
src/pages/getting-started/developers.md
src/pages/migration/index.astro

Updates Storybook links to match updated Storybook located in this PR: https://github.com/RocketCommunicationsInc/astro/pull/1349

chore: update links to match updated storybook

---

src/pages/releases/index.astro

Updates WC versions and last updated date

chore: update release dates

---

src/pages/components/accordion.md
src/pages/components/checkbox.md
src/pages/components/clock.md
src/pages/components/container.md
src/pages/components/global-status-bar.md
src/pages/components/input-field/index.md
src/pages/components/log/index.md
src/pages/components/notification-banner/index.md
src/pages/components/pop-up.md
src/pages/components/progress/index.md
src/pages/components/radio-button.md
src/pages/components/secondary-nav-example/index.md
src/pages/components/segmented-button.md
src/pages/components/slider/index.md
src/pages/components/switch.md
src/pages/components/tabs/index.md
src/pages/components/textarea/index.md
src/pages/components/timeline.md
src/pages/components/toast.md
src/pages/components/tooltip.md
src/pages/components/tree.md

Fixes the links I missed in earlier PR.

fix: links on components

---

src/pages/platforms/astro-for-grafana.md

Updates the Astro for grafana page with new version info.

docs: update grafana page

---

src/pages/design-tokens/reference/index.astro

[JIRA Ticket](https://rocketcom.atlassian.net/browse/AP-248)
There was a small handful of reference tokens that were missing from the reference documentation page. This PR adds them in.

fix(reference-token-docs): add missing reference tokens to reference page

---

src/pages/releases/index.astro

This PR updates the package versions and dates on the Releases page.

chore: updating versions

---

src/pages/releases/index.astro

Update version numbers
Dark from 7.8.2 to 7.8.3
Light from 7.6.1 to 7.6.2
Wireframe from 7.6.1 to 7.6.2

update to dark 7.8.3, light and wireframe to 7.6.2

---

src/data/glossary.json

- Added CAB item to glossary
- Added DI item to glossary
(to go with updates to the classification markings page)

Add CAB and DI to Glossary
