RocketCommunicationsInc/astro-www

src/components/site-search/site-search.fe.ts
huzzzah, we can now pull in content from next.astrouxds.org instead of the current live site. You can test this works by searching for "design tokens". Those pages only exist on next.
Unfortunately, the results for 'design tokens' are kind of a mess. We'll probably need to tweak the algolia juice somehow. 
Adding to the nice-to-have-list, it would be great if the `indexName` here could be dynamic: on main, just be `astrouxds`, on next, `astrouxds-next` so that we don't have to worry about anything when we deploy
=> feat: use our next site for algolia index

src/pages/getting-started/index.md
I've added the copyright block quote from the old getting started page to the new site, but the block quotes do not seem to be getting pick up? 
When I preview the getting-started md file in vscode the block quotes are working.
=> refactor: add copyright blockquote from old site

src/layouts/docs/docs-layout.css
This improves the first-time developer experience of looking at the docs layout CSS by annotating blocks of code, and by replacing usages of `max()`, which was chosen because it was shorter to write, with `calc()`, which expresses the intent of the code more clearly.
=> chore: improve docs layout css

src/pages/getting-started/index.md
I went ahead and hard coded the copyright year on the getting started page for now.
=> refactor: hard code copyright year on getting started page

src/components/contribution-footer/contribution-footer.astro, src/layouts/docs/docs-layout.astro
I've added a contirbutions-footer component and empty css file for now. There is a dynamic link which will need to be handle  somehow not really able to hard code it unless we link somewhere else. It deep links right to the MD file on the github repo to suggest an edit.
Example dynamic link: https://github.com/RocketCommunicationsInc/astro/edit/next/packages/astro-uxds/_content/getting-started/developers.md
=> feat: add contributions-footer to docs-layout

src/components/home/articles/home-articles.css
Fixed the padding/margins/spacing on the articles body, text, and buttons. I couldn't get the spacing to be 88px like in the Figma design without there being a scroll bar, but I maxed out the space between the articles as close as I could. I noticed one interesting thing, there is border-radius: 3px 3px 0px 0px on 3 of the article images, but not the forth (which is the third image from the left). That matches the Figma design exactly. So I'm thinking there was a small error in the Figma file.
=> (homepage-redesign): fixed padding and spacing on articles

src/components/site-navigation/site-navigation.css
Mobile nav was getting cut in half when search was activated and the top navbar would stay cut if the search was open even if the nav was closed. The solution was a desktop style that was not properly scoped for only viewports in the non-mobile range. I scoped it. Tested in Chrome and emulator in Safari, all good.
=> (fix): mobile nav width breaking on search

src/pages/design-guidelines/color.md
We added a bit of script that adds colors next to the hex codes and color CSS names/ Design tokens on [this page](https://www.astrouxds.com/design-guidelines/color/). [ASTRO-4840](https://rocketcom.atlassian.net/browse/ASTRO-4840)
Co-authored-by: Jonathan Neal <jonathantneal@hotmail.com>
=> Add colors to /design-guidelines/color/ migration tables

src/pages/fd-service-ux-design/about-the-fd-designs.md
The screenshots for the Data Display and Log Utility where incorrect. The correct ones should display now.
=> (fix): Fixing incorrect screenshots on the FDS page

src/components/site-search/site-search.client.ts, src/components/site-search/site-search.css
Our new search did not have some of the keyboard controls that the search on the old website had. This PR now allows a keyboard user to:
- focus search input on cmd + k or ctrl + k
- ArrowUp and ArrowDown navigate results once the first result is focused.
- Enter selects result
- Escape clears results and search input
=> (fix): Restore keyboard controls on search

src/pages/patterns/notifications.md
Fixed a sentence indicating that there were more notifications displayed in the image than there actually were
=> fix a typo on notifications page

src/pages/components/icons-and-symbols.md, src/pages/components/status-symbol.md
The Status Symbol and Icons and Symbols page both carried recommendations to include the title attribute to increase accessibility. This is no longer recommended so these sections and references were removed from each page.
=> (fix): Removing recommendations to include title attribute

src/pages/patterns/navigation.md
Just as we've change the language in our repository to eliminate the term _master_, I suggest that this navigation pattern be renamed.
I did not change the name of a linked image, also called master-detail.
=> Rename Master-detail navigation to List-detail navigation

src/pages/components/icons-and-symbols.md
Corrects an info box that had the wrong information for what color the borders of status symbols should be in light theme.
=> docs(icons-and-symbols): fix status symbol border color

src/components/compliance/compliance-aside.css, src/data/compliance.json
There was a trailing 'new' in the compliance UI box at the bottom of the Dialog and Focus State pages. This is the rule status and it was un-styled. I have copied over the styles from the Compliance page so that they now show up in the Compliance Aside.
=> fix(compliance): Removing word 'new' from compliance UI on dialog and focus state pages

src/components/icon-search/parts/icon-groups.astro
This is a one-line change that sorts the icons in their groups alphabetically. It does _not_ sort the groups alphabetically as then Astro would not be first, and I think it should be.
=> chore(icon-library): Sorting icons in their groups alphabetically

src/components/icon-search/icon-search.css
icon library in safari at screen sizes over 1600 broke.. Turns out that it wasn't polyfilling a media query correctly. I swapped it around and it figured itself out.
=> fix transpile error for media query

src/components/icon-search/parts/side-panel.ts
This removes the `icon-` prefix from icon IDs, as this prefix is not actually found in our web components.
[🌐 Preview](https://deploy-preview-113--astrouxds.netlify.app/icon-library/)
=> Remove `icon-` prefix from icons

src/components/home/community/home-community-events.astro, src/components/home/community/home-community-events.constants.ts, src/components/home/community/home-community-events.update.js
[ASTRO-5649](https://rocketcom.atlassian.net/browse/ASTRO-5649)
Google API sends all day events as just a date with no time zone info attached, so I had two add in a special exception to make them show the correct date in all time zones.
=> fix(event calendar) All day events now always show on the first day

src/components/home/community/home-community-events.astro, src/components/home/community/home-community-events.constants.ts, src/components/home/community/home-community-events.update.js, src/components/home/community/home-community.css
[ASTRO-5682](https://rocketcom.atlassian.net/browse/ASTRO-5682)
**Problem:** The events calendar on the home page was not set up to handle events that span multiple days.
**Work:** In order to figure out how multi-date events might be displayed, I got together with Steve M. and Andrew. Steve created a new figma design which rearranged the events calendar information, making room for more date data.
I then:
- Implemented the new design
- Created some code so that start and end date of multi-day events would be displayed
- Set an exception for single day events where it would display the date and 'All Day'
- Tested both the JS and nonJS versions of this, as well as the server side and client side rendering.
Going to link the preview to Steve for Design review and tweak a few things.
=> fix(events cal) update events calendar to handle all day and multi-day events

src/components/home/articles/home-articles.css, src/components/home/banner/home-banner.astro, src/components/home/banner/home-banner.css, src/components/home/community/home-community.css, src/components/home/explainer/home-explainer.css, src/components/home/version/home-version.astro, src/components/home/version/home-version.css, src/components/site-navigation/client/h-navigation-disclosure.css, src/components/site-navigation/site-navigation.css, src/components/site-skipto/site-skipto.astro, src/components/site-skipto/site-skipto.css, src/data/home-banner.json, src/layouts/default/default-layout.astro, src/layouts/default/style/layout.css, src/layouts/docs/docs-layout.astro, src/layouts/docs/style/layout.css, src/layouts/home/home-layout.astro, src/layouts/home/home-layout.css, src/layouts/new-docs/style/layout.css, src/pages/index.astro
<details><summary><strong>Fix partially hidden “Skip to Main Content” link</strong></summary><br />
When the “Skip to Main Content” link is focused, it is obscured on larger screens, making it harder to notice.
**Before**:
**After**
Additionally, the “Skip to Main Content” link is missing from the homepage, which is restored.
---
</details>
<details><summary><strong>Fix missing styles for non-JS navigation on small screen widths</strong></summary><br />
If JS fails to load, our site navigation is open by default. On small screens, the fallback experience makes the home “Astro” link inaccessible, and displays the navigation in a way that is difficult to use when compared to the larger screen fallback experience.
**Before**:
**After**:
---
</details>
<details><summary><strong>Fix missing …
=> Minor Layout Styling Fixes

src/data/compliance.json
Fixed typos in the Components compliance section:
4.2.2, 4.7.2, and 4.12.3
=> docs(compliance): fixed typos in components section

src/data/compliance.json
Fixed name of Secondary Button in rule 4.1.8 from the old name (Outlined Button).
=> fix(compliance): fixed secondary button name

src/pages/getting-started/designers.md
This updates the getting started for designers page with new text regarding the fonts we use from google, (roboto, roboto mono). The text was pulled straight from the design confluence page linked in the ticket. 
Links that link out to external pages where verified to open in a new tab, as per the design confluence doc as well. 
JIRA: https://rocketcom.atlassian.net/browse/ASTRO-5609
=> docs: updated getting started for designers doc with font info

src/data/compliance.json
[Astro-5743](https://rocketcom.atlassian.net/browse/ASTRO-5743)
Added the Deprecated indicator to Breadcrumb compliance rule 3.7.2: Breadcrumb shall not extend beyond 7 items.
=> doc(breadcrumb) add deprecated to 7 item rule

src/data/compliance.json, src/pages/design-guidelines/color.md
We need to remove compliance rule 2.1.2 from the Colors compliance rule list since it is now irrelevant (we no longer have Tag palettes) and update text organization to match latest changes in our internal documentation.
https://rocketcom.atlassian.net/browse/ASTRO-5783
=> docs(compliance): removed irrelevant color rule

src/pages/components/button.md
Removed outdated rule of thumb related to the compliance rule that is deprecated.
No Jira ticket. Made the change on the internal Confluence page already.
=> docs(buttons): removed outdated rule of thumb

src/components/home/community/home-community-events.eventToggleHandler.js, src/components/home/community/home-community-events.update.js, src/components/home/community/home-community.css
On the home page I made the entire event box interactive.
[ASTRO-5827](https://rocketcom.atlassian.net/browse/ASTRO-5827)
I checked keyboard controls and they still function as one would expect. Also, links in the event details area still supersede the on click functionality so they can be clicked.
=> make show/hide event onclick entire event box

src/layouts/new-docs/style/specs.css, src/pages/components/button/specs.md, src/pages/components/input-field/specs.md, src/pages/components/select/specs.md, src/pages/components/slider/specs.md, src/pages/components/textarea/specs.md
[Astro-5998](https://rocketcom.atlassian.net/browse/ASTRO-5998)
Verify the sizes between figma and spec pages for images. Also a couple of css changes to allow the example images to respond at a higher screen width.
=> docs(specs) update image sizes to better match figma

src/components/icon-search/icon-search.css, src/layouts/new-docs/style/page.css
This PR fixes the issue where the icons in the icon library were not respecting the min-width, and the icon search bar was hidden under the nav bar because it is now sticky.
=> Fixing icon size and where the search sticks on mobile.

src/pages/components/classification-markings.md, src/pages/components/status-symbol.md, src/pages/design-guidelines/color.md, src/pages/design-guidelines/grid.md, src/pages/design-guidelines/typography.md, src/pages/design-tokens/installation.md, src/pages/getting-started/developers.md, src/pages/getting-started/index.md, src/pages/grm-service-ux-design/grm-dashboard.md, src/pages/grm-service-ux-design/grm-equipment-manager.md, src/pages/grm-service-ux-design/grm-schedule.md, src/pages/ttc-service-ux-design/ttc-command.md, src/pages/ttc-service-ux-design/ttc-investigate.md, src/pages/ttc-service-ux-design/ttc-monitor.md
This change updates markdown tables to use an overflow fix that improves the styling on smaller-width devices.
=> Update all Markdown tables to use overflow fix

src/components/feedback-widgets/feedback-widget-sticky/feedback-widget.css
This change updates the height on the feedback widget so that it cannot exceed the height of the page minus the space required for the site navigation on small-width devices.
=> Fix feedback widget height on small height devices

src/components/feedback-widgets/feedback-widget-custom-element.ts, src/components/feedback-widgets/feedback-widget-sticky/feedback-widget.css, src/components/icon-search/icon-search.client.ts, src/components/icon-search/icon-search.css, src/components/icon-search/parts/side-panel.shadow.css, src/layouts/default/style/sanitize.css
This PR includes:
- A fix for feedback widget slide-in animation on mobile. previously, the slide-in would push the content and zoom the page, but only on actual mobile devices. This fix changes the positioning of the widget from fixed to sticky, but only on mobile viewports. To account for the widget tab stopping at the footer an intersection observer was added on the footer which adds and removes a scroll event listener that dynamically positions the feedback widget tab on scroll, but only when the user is scrolling through the footer.
- A fix on the icon library page where the feedback widget tab was overlaying the icon side-panel when open. Now it falls underneath it.
- A fix for the icon library side-panel on mobile. The nav is now sticky on mobile, and the positioning of the icon …
=> fix(feedback-widget): solution for widget slide-in on mobile

src/components/site-navigation/site-navigation.css
This PR fixes an issue where if some of the trees in the nav were expanded the shorter pages would then expand to fill that space as well, leaving weird whitespace at the bottom that is more noticeable now with the sticky widget.
=> fix(nav + content) Fixing content expanding to fit nav-height and leaving whitespace at bottom

src/components/home/articles/home-articles.css, src/components/home/community/home-community.css, src/components/home/explainer/home-explainer.css
This fix removes the styling `@media (hover: hover)` on the homepage blocks which was preventing the clickable link that gets expanded using a `::before` from working on mobile.
=> fix(homepage): Fixing homepage blocks not being clickable on mobile

src/data/navigation.json
This PR is a tiny change to the navigation JSON file that moves the Application State link in the nav down below the divider line, as it is technically a component.
=> fix(nav): moving app state link down below the divider line in components on the nav.

src/layouts/new-docs/style/heading-anchors.css
Just a small tweak. I was asked if we could move the anchor link images in the headers over to the right on the /next/ branch. People seemed to like it but I wanted to wait to finalize until I could build off main.
[ASTRO-6081](https://rocketcom.atlassian.net/browse/ASTRO-6081)
=> css(anchor links) move the anchor ing to the end of headings rather than the beginning

.vscode/settings.json, src/data/asset-status.d.json, src/data/compliance-footer.d.json.ts, src/data/compliance.d.json.ts
Use file nesting to better organize related files in VSCode.
=> Use file nesting in VSCode

src/components/site-navigation/site-navigation.css
This PR adds the search bar back into the nav on mobile. For some reason it was set to `display: none`, so having it hidden was intentional.
=> fix(mobile-nav): adding search back to mobile nav

src/layouts/default/style/layout.css, src/layouts/new-docs/style/page.css
This fix adds `block-size` 100% to the `<main>` element.
=> fix(feedback widget): not sticking to bottom on 404 page

package.json, src/pages/releases/index.astro
just bumps the WC version on the releases page
=> chore: bump WC version

src/pages/releases/index.astro
Updates figma libs on releases page, updates the 'last updated' date, adds new figma lib "astro templates"
=> chore: update figma releases

src/components/component-playground/Control/Menu.ts
[ASTRO-6217](https://rocketcom.atlassian.net/browse/ASTRO-6217)
the select menu control was not resetting properly on Example change. It would become disconnected from the example it was supposed to be controlling.
This ultimately had to do with examples looking for control.value but in this case the value lived on control > select.value
Implemented a fix where (on input) control.vale = select.value
Also added some robustness so that if there IS not a default select value it defaults to the first option.
=> fix(playground) fix menu/select control bug

src/pages/getting-started/developers.md
* Adds an immediate callout to Storybook, where all of our getting started content lives. 
* Removed a lot of flat out old and incorrect information (theres no CSS "library" anymore, Roboto Mono). 
* Removed the material theme links. These are very outdated, provide little value, and confuse users who might be looking to use Astro in Material UI/Angular Material 
*
=> docs: update dev getting started

src/components/component-playground/IFrameLayout.astro, src/data/component-playgrounds.record.d.json.ts, src/data/component-playgrounds.record.json
[Astro-6083](https://rocketcom.atlassian.net/browse/ASTRO-6083)
Ultimately I just added an import for the roboto font in the iframe template for playground. The components then used it appropriately.
While I was in there I realized that we're not cherrypicking anymore so we don't need the 'dependencies' portion of the component playground json file. so I removed those as a minor cleanup.
=> feat(playground) add roboto to rux-components

src/layouts/docs/docs-layout.astro
[Astro-6312](https://rocketcom.atlassian.net/browse/ASTRO-6312)
Tweaked the logic so that if the last segment of the page url doesn't match the last segment of the file url (sans file extension) it will add the last segment of the file url to the link.
=> fix(Contribution Footer) fix 'propose a change' link logic

src/data/component-playgrounds.record.json
[ASTRO-6328](https://rocketcom.atlassian.net/browse/ASTRO-6328)
Double checked the other components against storybook and it looks like the others that should have invalid props do have them.
=> fix(rux-input) add invalid switch to Input on playground

src/pages/releases/index.astro
Release 7.14 for WC's. 
No design releases this time
=> chore: bump WC version in releases for 7.14

src/data/component-playgrounds.record.json, src/pages/components/status-symbol.md
Added a playground for rux-status. Must have gotten lost in the shuffle.
=> docs(status symbols) add rux-status playground

netlify.toml, src/data/compliance-footer.json, src/data/navigation.json, src/pages/compliance/index.astro, src/pages/compliance/r2c2-design-compliance/index.astro, src/pages/design-guidelines/compliance/index.astro
This PR is to updates the main nav, template filename, redirects and links from EGS to R2C2. Another update with content will be coming. Happy to do those for a single PR if that’s preferable.
=> EGS to R2C2

src/data/asset-status.json, src/data/component-playgrounds.record.json, src/data/navigation.json, src/pages/components/card.md, src/pages/components/toast.md
Adds the toast page, updates component playground with toast, and updates a very small issue I found on card where the rules of thumb were not list-items. 
Ticket: https://rocketcom.atlassian.net/browse/ASTRO-6427
I'm not sure if we need to have toast-stack as part of the playground or not? It looks fine, but I'm worried that a dev may not know about it and just use toast by itself based on this page. 
Also, should we call out that it's technically in beta?
=> feat: add toast page, update playground with toast

src/components/contribution-footer/contribution-footer.astro, src/layouts/docs/docs-layout.astro
[ASTRO-6474](https://rocketcom.atlassian.net/browse/ASTRO-6474)
I think something changed in a recent AstroJS update (as stuff tends to do). During the site build process all astro files get changed into mjs files. This apparently happens BEFORE the script I wrote to grab their file extensions as part of the GitHub url link. So I added a small hack to say that if the fileExtension is 'mjs' use 'astro' in the link instead.
That seems to have fixed it everywhere it was an issue.
=> test fix for files

src/pages/components/timeline.md
This PR updates the documentation on the timeline component, specifically under the 'Track' sub header to expand on guidance about the track title width.
[JIRA-5684](https://rocketcom.atlassian.net/jira/software/c/projects/ASTRO/boards/113?quickFilter=186&selectedIssue=ASTRO-5684)
=> chore: updating timeline guidance for track title width

src/pages/components/card/specs.astro, src/pages/components/log/specs.astro, src/pages/components/push-button/specs.astro, src/pages/components/tag/specs.astro
Some of the specs pages were missing their descriptions. Probably happened when we switched them too .astro I've added them back. :)
=> add descriptions to specs pages missing them

src/pages/icon-library/index.astro
Since we put up this description, Google has clarified their old icons as "Material Icons" and now a different set of icons called "Material Design Icons" are online and available. Changing the description to clarify that we're using the Material Icons here.
=> Update Icon Set Name for Material Icons

src/components/feedback-widgets/feedback-widget-custom-element.shadow.css, src/components/feedback-widgets/feedback-widget-custom-element.shadow.html, src/components/feedback-widgets/feedback-widget-custom-element.ts, src/components/source-code-access/source-code-access.astro, src/components/source-code-access/source-code-access.css, src/components/source-code-access/source-code-access.ts, src/data/source-code-access.json
This PR includes two changes:
- An additional textarea in the source code request modal to include a description of the requester's use case. This gets mapped in the backend to our Google sheet and included in both the notification and confirmation emails.
- An additional checkbox in the feedback widget for the user to check if they would like a response. This makes the email field required. This is also mapped to our backend and to an additional column in our Google sheet, and in the emails that are auto-generated.
- Some additional cleanup and tuning of the feedback widget.
=> feat(feedback widget / source code request): use description in source code request and email required in feedback widget

src/pages/design-tokens/component/index.astro, src/pages/design-tokens/component/light.astro, src/pages/design-tokens/system/index.astro, src/pages/design-tokens/system/light.astro, src/utils/tokens.ts
There were a handful of missing tokens on the system and component pages. The following have now been added to the light and dark sections of each page:
**Component**
- Push Button
- Tab
**System**
- Opacity
- Focus Border Width
- Shadow Overlay
- Focus Spacing
=> fix(design-tokens): adding missing system and component tokens

src/pages/releases/index.astro
I was on the Releases page and saw that the compliance was still listed as EGS compliance instead of Astro compliance, so I'm trying to make that word change on the Releases page.
=> Fix: Update index.astro EGS to Astro Compliance

netlify/functions/stripe.js
What we are doing: 
This changes how products are managed with Stripe. Previously we were sending a product definition object from the front end to Stripe. 
Now we define the product in the Stripe [Dashboard.](https://dashboard.stripe.com/test/products?active=true) 
Why?: 
This has several benefits.
- Allows the persistence of the item being purchased in the Stripe Dashboard. (previously the item object created and "archived" item that was only findable from the transaction and not in the products section of the Stripe Dashboard
- It allows us to set an expected tax code on the product enabling us to take advantage of the Stripe tax features. (ie. taxes will be collected if the area for the address entered is registered with Stripe by accounting.
- Price changes and tax collection can be …
=> Reference dashboard products

src/pages/design-tokens/system/index.astro, src/pages/design-tokens/system/light.astro
https://rocketcom.atlassian.net/jira/software/projects/AP/boards/119?assignee=712020%3A6a79a1e3-7381-4656-9516-c09792ad18be%2C60e2c268bd7f5d006886d1bf&selectedIssue=AP-495
There is a lot of info on the card above.
There were three reasons that the box shadow area was empty.
Property Filter: the system function is filtering tokens where token.property === property, but for boxShadow tokens, we pass undefined which won't match the actual properties like "overlay" or "inner".
System/Theme Level: the system function only returns tokens where tokenLevel === 'system' || tokenLevel === 'theme', but the boxShadow tokens in docs.json mostly have tokenLevel === 'component'.
Component Null: our filter requires token.component === null, but most boxShadow tokens have a specific component like "card" …
=> fix empty shadow overlay section

src/pages/releases/index.astro
Returned version number for Figma icon library from 2.0.0 to 1.1.0 since we rolled back the breaking change.
https://rocketcom.atlassian.net/browse/AP-642
=> docs: roll back figma icon library version number

src/pages/getting-started/developers.md, src/pages/releases/index.astro
Add Package Versioning Documentation
This adds documentation to the releases page explaining how different packages in the Astro ecosystem receive version updates.
Changes:
- Minor content update in developer getting started guide mentioning React and Angular wrapper packages
- Added new "Package Versioning" section to [index.astro] that explains:
- How core changes affect all wrapper packages (web components, React, Angular)
- How framework-specific changes only affect individual packages
- Clear guidelines for when major vs minor version bumps occur
- Updated version numbers in the releases table to reflect current package versions:
-- Web Components: 7.25.2 → 7.27.0
-- Angular Components: 7.25.2 → 8.0.0 (added as new row)
-- React Components: 7.25.2 → 7.27.0 (added as new row)
=> Update the copy and table to explain versioning strategy
